### ISSUE TITLE
json ファイルへの書き込み時に permission denied

### ISSUE THREAD

**Issue by tasuwo** [selab601/ETRobocon-Logger#4]
開発環境ではうまく動いていたけれど，パッケージングしたアプリからファイル保存を行おうとすると permission denied になる．

![t](https://cloud.githubusercontent.com/assets/10893464/24292541/1f5448ec-10d1-11e7-9b0f-ffa6ca61236a.png)

おそらく，ファイルパスがきちんと指定できていないのが問題．

[パッケージングしたElectronアプリケーションでファイル操作時にpermission deniedになった場合の対処 - Qiita](http://qiita.com/takeyuichi/items/100d4a5b89df43855986)

**Comment by motokii** [comment]
Pull request #10 で修正
