### ISSUE TITLE
コンソール上から起動するとエラーが出る

### ISSUE THREAD

**Issue by motokii** [selab601/ETRobocon-Logger#6]
`run.sh`を実行すると最初にエラーが出てきます。
ログを読み込むことはできるのですがBluetoothが使えません。
どうすれば良いのでしょうか…

nodeとnpmのバージョン
- node: v4.4.6
- npm: 5.0.4

![screenshot](https://user-images.githubusercontent.com/11635742/27711768-22170418-5d5f-11e7-87de-118c632a5882.png)

```
Uncaught Exception:
Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/motoki/et2016/ETRobocon-Logger/node_modules/bindings/bindings.js:76:44)
```

**Comment by tasuwo** [comment]
あ、このエラー知ってるな。確か、node と Electron の abi のバージョンが異なっている時に出るエラーだ。

Electron の ABI バージョンっぽいやつ↓

> [electron-abi](https://www.npmjs.com/package/electron-abi)

node の ABI バージョン↓

> [リリース一覧 | Node.js](https://nodejs.org/ja/download/releases/)

node v4.4.6 の ABI バージョンが **46**、electron は `package.json` に記述されている通り v1.1.3 なので ABI バージョンが **48**、ということでエラーが出ているのだと思います。

node のバージョンを切り替えて、`node_modules` を削除して、`npm install` し直すといけるかもしれない！行けなかったらまた考えよう。

参考になるかわからないけど↓

> [Module version mismatch. Expected 48, got 47. · Issue #453 · electron-userland/electron-builder](https://github.com/electron-userland/electron-builder/issues/453)

**Comment by tasuwo** [comment]
`package.json` 内に `engine` という項目を追加すると node のバージョンを指定できるらしいので、これを追加すると良いと思います。
俺が気付いた時にやっておけばよかった...

> https://docs.npmjs.com/files/package.json#engines

**Comment by tasuwo** [comment]
うーん、`engine` の項目は、このアプリケーションをパッケージとしてインストールした時のための制約を書いておく箇所で、dependencies をインストールする時の制約としては動作しないっぽい。
手元で書いて確かめて見たけど、何もエラーが出なかった...
README に追記するのが良いのかな？

> http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html
> https://github.com/npm/npm/issues/3672

**Comment by motokii** [comment]
ありがとうございます！
nodeのバージョンをv6.0.0にして`npm install`し直したら動きました
